CREATE DATABASE 'd:\data\tumblelog.sdf' DATABASEPASSWORD 'tumble1234';
CREATE TABLE posts (postid INT IDENTITY PRIMARY KEY, title NVARCHAR(250) NOT NULL, body NVARCHAR(4000) NOT NULL, slug NVARCHAR(100), created_on DATETIME NOT NULL);
CREATE TABLE comments (postid INT, body NVARCHAR(200) NOT NULL, author NVARCHAR(150) NOT NULL, created_at DATETIME NOT NULL);