CREATE DATABASE 'tumblelog.sdf' DATABASEPASSWORD 'tumble1234';
CREATE TABLE post (postid INT IDENTITY PRIMARY KEY, title NVARCHAR(250) NOT NULL, body NVARCHAR(4000) NOT NULL, slug VARCHAR(100), created_at DATETIME NOT NULL);
CREATE TABLE comment (postid INT, body NVARCHAR(200) NOT NULL, author NVARCHAR(150) NOT NULL, created_at DATETIME NOT NULL);